services:
  bot:
    container_name: oxbot
    image: communityox/oxbot:latest
    build: .
    restart: unless-stopped
    command: bun run start:production
    volumes:
      - db-data:/app/prisma
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=file:/app/prisma/data.db

volumes:
  db-data:
