services:
  bot:
    image: communityox/oxbot:latest
    build: .
    restart: unless-stopped
    depends_on:
      - db
    command: bun run start:production
    volumes:
      - db-data:/app/prisma
    env_file:
      - ./.env

  db:
    image: mariadb:11.7
    working_dir: /var/lib/mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MARIADB_DATABASE=${MARIADB_DATABASE}"
      - "MARIADB_USER=${MARIADB_USER}"
      - "MARIADB_PASSWORD=${MARIADB_PASSWORD}"

volumes:
  db-data:
